### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by codingedgar** [Zaid-Ajaj/Npgsql.FSharp#51] opened 2020-03-16 04:56 UTC
Thank you so much for such a good lib 👏 love it! 

I'm wondering how could I add configuration for logging ? https://www.npgsql.org/doc/logging.html 

I tried to do 
```fs
NpgsqlLogManager.Provider <- ConsoleLoggingProvider(NpgsqlLogLevel.Debug, true, true)
NpgsqlLogManager.IsParameterLoggingEnabled <- true
```

before connecting but the logging is not working.

Thank you 🙏

**Comment by Zaid-Ajaj** [comment] 2020-03-18 22:02
Hello there @edgarjrg, 

I actually haven't played with the logging feature of Npgsql. I will certainly give it a try and see why it isn't working :smile:

**Comment by Zaid-Ajaj** [comment] 2020-12-05 23:14
Hi there @codingedgar, I thought of trying logging with Npgsql as of the latest bits: 
 - Npgsql v5.0
 - Npgsql.FSharp v3.12.2 

And logging seems to work properly:

![logging](https://user-images.githubusercontent.com/13316248/101267348-db8c0080-3757-11eb-9a6c-227744ab34a5.png)

Can you please give it a try? Would be nice to close the issue if the problem is resolved 😄

**Comment by codingedgar** [comment] 2020-12-05 23:40
I'm going to try it Monday 💛 thank you 🙌

**Comment by Zaid-Ajaj** [comment] 2020-12-29 00:46
I'll assume this is resolved in latest, reopen the issue if the problem persists ;)

**Closed** 2020-12-29 00:46 UTC
Labels: waiting-feedback, works
