### ISSUE TITLE
Unexpected behavior on netcoreapp3.1

### ISSUE THREAD

**Issue by Disinterpreter** [Zaid-Ajaj/Npgsql.FSharp#84] opened 2021-01-31 13:07 UTC
The example

```fsharp
    [<ServerEvent( Event.ResourceStart )>]
    let start =
        Console.WriteLine("aaaaaaaaaaaaaaaaaa")
        
        let connString = "Host=HOST;Username=NAME;Password=PASSOWD;Database=DBNAME";
        let result = 
            connString
            |> Sql.connect
            |> Sql.query "SELECT 99 + 33 as num"
            |> Sql.executeAsync(fun read ->
                {
                    Sum = read.int "num"
                })

        Console.WriteLine(result)
        1;
```

Got: 
```
Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Core.FSharpResult`2[Microsoft.FSharp.Collections.FSharpList`1[pressf.auth.Summ],System.Exception]]
```

Screenshot:
![image](https://user-images.githubusercontent.com/3816155/106384889-6565ec00-63de-11eb-8d9d-45fda7a5e8ba.png)

**Comment by trungdo-epi** [comment] 2021-02-26 05:24
You should use `Sql.executeRowAsync` instead of `Sql.executeAsync`.

**Comment by Zaid-Ajaj** [comment] 2021-02-26 05:56
I think the problem is using `Sql.execute` instead of the async equivalent in the first place

**Comment by Disinterpreter** [comment] 2021-02-26 06:36
> 
> 
> I think the problem is using `Sql.execute` instead of the async equivalent in the first place

Sure, it is work for sync, I solved it after posting my issue, but how to work with async query? 🤔

**Comment by Zaid-Ajaj** [comment] 2021-02-26 16:36
>  but how to work with async query? 

You need to run the code in the context of `async` or `task` (depending on which namespace you are using)
```fs
task {
  let! result = 
      connString
      |> Sql.connect
      |> Sql.query "SELECT 99 + 33 as num"
      |> Sql.executeAsync(fun read -> { Sum = read.int "num" })

  // do something with result
}
```

**Comment by Zaid-Ajaj** [comment] 2021-03-05 03:05
I believe the issue is resolved so I will close it now 😄

**Closed by Zaid-Ajaj** 2021-03-05 03:05 UTC

**Comment by Disinterpreter** [comment] 2021-03-05 06:46
> 
> 
> I believe the issue is resolved so I will close it now 😄

indeed. just put more examples to readme please.

**Comment by Zaid-Ajaj** [comment] 2021-03-05 08:42
I will be creating a documentation website for the next release
